apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: deis-monitor-influxdb
  namespace: deis
  labels:
    heritage: deis
  annotations:
    helm-keep: "true"
    component.deis.io/version: {{env "INFLUXDB_GIT_TAG" | default .influxdb.dockerTag}}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: deis-monitor-influxdb
  template:
    metadata:
      labels:
        app: deis-monitor-influxdb
    spec:
      containers:
      - name: deis-monitor-influxdb
        image: quay.io/{{.influxdb.org}}/influxdb:{{env "INFLUXDB_GIT_TAG" | default .influxdb.dockerTag}}
        imagePullPolicy: {{.influxdb.pullPolicy}}
{{- if or (.influxdb.limits_cpu) (.influxdb.limits_memory)}}
        resources:
          limits:
{{- if (.influxdb.limits_cpu) }}
            cpu: {{.influxdb.limits_cpu}}
{{- end}}
{{- if (.influxdb.limits_memory) }}
            memory: {{.influxdb.limits_memory}}
{{- end}}
{{- end}}
        ports:
        - containerPort: 8083
          name: admin
        - containerPort: 8086
          name: transport
          protocol: TCP
        - containerPort: 8084
          name: ssltransport
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /ping
            port: 8086
          initialDelaySeconds: 1
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /ping
            port: 8086
          initialDelaySeconds: 1
          timeoutSeconds: 1
