#helm:generate helm tpl -d $HELM_GENERATE_DIR/tpl/generate_params.toml -o $HELM_GENERATE_DIR/manifests/deis-workflow-manager-deployment.yaml $HELM_GENERATE_DIR/tpl/deis-workflow-manager-deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: deis-workflow-manager
  namespace: deis
  labels:
    heritage: deis
  annotations:
    helm-keep: "true"
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: deis-workflow-manager
  template:
    metadata:
      labels:
        app: deis-workflow-manager
    spec:
      serviceAccount: deis-workflow-manager
      containers:
      - name: deis-workflow-manager
        image: quay.io/{{.workflowManager.org}}/workflow-manager:{{env "WORKFLOW_MANAGER_GIT_TAG" | default .workflowManager.dockerTag}}
        imagePullPolicy: {{.workflowManager.pullPolicy}}
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: PORT
          value: "8080"
        - name: VERSIONS_API_URL
          value: {{.workflowManager.versionsApiURL}}
        - name: DOCTOR_API_URL
          value: {{.workflowManager.doctorApiURL}}
        - name: POLL_INTERVAL_SEC
          value: "43200"
        - name: CHECK_VERSIONS
          value: "true"
        - name: API_VERSION
          value: "v2"
        - name: DEIS_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports:
        - containerPort: 8080
