apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: deis-logger-fluentd
  namespace: deis
  labels:
    heritage: deis
spec:
  template:
    metadata:
      name: deis-logger-fluentd
      labels:
        heritage: deis
    spec:
      serviceAccount: deis-logger-fluentd
      containers:
      - name: deis-logger-fluentd
        image: quay.io/deisci/fluentd:git-c2910f1
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        env:
        - name: SYSLOG_HOST
          value: $(DEIS_LOGGER_SERVICE_HOST)
        - name: SYSLOG_PORT
          value: $(DEIS_LOGGER_SERVICE_PORT_TRANSPORT)
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
