apiVersion: v1
kind: Service
metadata:
  name: deis-router
  namespace: deis
  labels:
    heritage: deis
  annotations:
    helm-keep: "true"
spec:
  type: LoadBalancer
  selector:
    app: deis-router
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: https
      port: 443
      targetPort: 6443
    - name: builder
      port: 2222
      targetPort: 2222
