apiVersion: v1
kind: ReplicationController
metadata:
  name: deis-workflow-manager
  namespace: deis
  labels:
    heritage: deis
spec:
  replicas: 1
  selector:
    app: deis-workflow-manager
  template:
    metadata:
      labels:
        app: deis-workflow-manager
    spec:
      serviceAccount: deis-workflow-manager
      containers:
      - name: deis-workflow-manager
        image: quay.io/deisci/workflow-manager:v2-beta
        imagePullPolicy: Always
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: WORKFLOW_MANAGER_PORT
          value: "8080"
        - name: WORKFLOW_MANAGER_VERSIONSAPIURL
          value: "https://versions.deis.com"
        - name: WORKFLOW_MANAGER_STAGINGAPIURL
          value: "https://versions-staging.deis.com"
        - name: WORKFLOW_MANAGER_DOCTORAPIURL
          value: "https://doctor.deis.com"
        - name: WORKFLOW_MANAGER_POLLING
          value: "43200"
        - name: WORKFLOW_MANAGER_CHECKVERSIONS
          value: "true"
        - name: WORKFLOW_MANAGER_APIVERSION
          value: "v2"
        - name: WORKFLOW_MANAGER_DEISNAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports:
        - containerPort: 8080
