apiVersion: v1
kind: ReplicationController
metadata:
  name: deis-database
  namespace: deis
  labels:
    heritage: deis
spec:
  replicas: 1
  selector:
    app: deis-database
  template:
    metadata:
      labels:
        app: deis-database
    spec:
      serviceAccount: deis-database
      containers:
        - name: deis-database
          image: quay.io/deisci/postgres:v2-beta
          imagePullPolicy: Always
          env:
            - name: POSTGRES_USER
              value: "deis"
            - name: POSTGRES_PASSWORD
              value: "changeme123"
          ports:
            - containerPort: 5432
          livenessProbe:
            exec:
              command:
                - is_running
            initialDelaySeconds: 30
            timeoutSeconds: 1
          volumeMounts:
            - name: minio-user
              mountPath: /etc/wal-e.d/env
            - name: database-creds
              mountPath: /var/run/secrets/deis/database/creds
      volumes:
        - name: minio-user
          secret:
            secretName: minio-user
        - name: database-creds
          secret:
            secretName: database-creds
