apiVersion: v1
kind: Service
metadata:
  name: deis-logger
  namespace: deis
  labels:
    heritage: deis
    app: deis-logger
spec:
  ports:
  - port: 80
    name: http
    targetPort: http
  - port: 514
    name: transport
    targetPort: 1514
    protocol: UDP
  selector:
    app: deis-logger