kind: ReplicationController
apiVersion: v1
metadata:
  name: deis-etcd-1
  namespace: deis
  labels:
    name: deis-etcd-1
spec:
  replicas: 1
  selector:
    name: deis-etcd-1
  template:
    metadata:
      labels:
        name: deis-etcd-1
    spec:
      containers:
        - name: deis-etcd-1
          image: quay.io/deis/etcd:2.0.0-alpha
          imagePullPolicy: IfNotPresent
          env:
            - name: DEIS_ETCD_CLUSTER_SIZE
              value: "1"
            - name: ETCD_NAME
              value: deis1
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          volumeMounts:
            - name: discovery-token
              readOnly: true
              mountPath: /var/run/secrets/deis/etcd/discovery
            - name: var-lib-etcd2
              mountPath: /var/lib/etcd2
      volumes:
        - name: discovery-token
          secret:
            secretName: deis-etcd-discovery-token
        - name: var-lib-etcd2
          hostPath:
            path: /data/deis/etcd2
