apiVersion: v1
kind: Pod
metadata:
  name: deis-tests
  namespace: deis
  labels:
    heritage: deis
spec:
  containers:
  - name: deis-e2e
    image: quay.io/deisci/deis-e2e:git-19f3efb
    imagePullPolicy: Always
    command: ["/bin/sh", "-c"]
    args: ["/bin/tests.test"]
  restartPolicy: Never
