apiVersion: v1
kind: Pod
metadata:
  name: deis-tests
  namespace: deis
  labels:
    heritage: deis
spec:
  restartPolicy: Never
  containers:
  - name: deis-e2e
    image: quay.io/deisci/deis-e2e:canary
    imagePullPolicy: Always
    command: ["ginkgo"]
    args: ["-slowSpecThreshold=120.00", "-nodes=15", "-noisyPendings=false", "-progress", "tests/"]
    env:
      - name: JUNIT
        value: "true"
    volumeMounts:
    - name: artifact-volume
      mountPath: /root
  - name: artifacts
    image: busybox
    imagePullPolicy: Always
    command: ["tail", "-f", "/dev/null"]
    volumeMounts:
    - name: artifact-volume
      mountPath: /root
  volumes:
  - name: artifact-volume
    emptyDir: {}
