#helm:generate helm template -o $HELM_GENERATE_DIR/manifests/deis-objectstorage-secret.yaml -d $HELM_GENERATE_FILE $HELM_GENERATE_DIR/tpl/deis-objectstorage-secret.yaml
#
# This is the main configuration file for Deis object storage. The values in
# this file are passed into the appropriate services so that they can configure
# themselves for persisting data in object storage.
#
# In general, all object storage credentials must be able to read and write to
# the container or bucket they are configured to use.
#
# When you change values in this file, make sure to re-run `helm generate`
# on this chart.

# Set the storage backend
#
# Valid values are:
# - filesystem: Store persistent data on ephemeral disk
# - s3: Store persistent data in AWS S3 (configure in S3 section)
# - azure: Store persistent data in Azure's object storage
# - gcs: Store persistent data in Google Cloud Storage
# - minio: Store persistent data on in-cluster Minio server
storage = "minio"

[minio]
org = "deisci"
pullPolicy = "IfNotPresent"
dockerTag = "git-0c71217"

[s3]
accesskey = "YOUR KEY HERE"
secretkey = "YOUR SECRET HERE"
# Any S3 region
region = "us-west-1"
# Your buckets.
registry_bucket = "your-registry-bucket-name"
database_bucket = "your-database-bucket-name"
builder_bucket = "your-builder-bucket-name"

[azure]
accountname = "YOUR ACCOUNT NAME"
accountkey = "YOUR ACCOUNT KEY"
registry_container = "your-registry-container-name"
database_container = "your-database-container-name"
builder_container = "your-builder-container-name"

[gcs]
# key_json is expanded into a JSON file on the remote server. It must be
# well-formatted JSON data.
key_json = '''Paste JSON data here.'''
registry_bucket = "your-regsitry-bucket-name"
database_bucket = "your-database-bucket-name"
builder_bucket = "your-builder-bucket-name"

[builder]
org = "deisci"
pullPolicy = "IfNotPresent"
dockerTag = "git-8df2568"

[slugbuilder]
org = "deisci"
pullPolicy = "IfNotPresent"
dockerTag = "v2.0.0-beta1"

[dockerbuilder]
org = "deisci"
pullPolicy = "IfNotPresent"
dockerTag = "v2.0.0-beta1"

[controller]
org = "deisci"
pullPolicy = "IfNotPresent"
dockerTag = "git-3c07d6c"

[slugrunner]
org = "deisci"
pullPolicy = "IfNotPresent"
dockerTag = "git-bcdeae2"

[database]
org = "deisci"
pullPolicy = "IfNotPresent"
dockerTag = "git-03ddca5"

[registry]
org = "deisci"
pullPolicy = "IfNotPresent"
dockerTag = "git-93d8fb2"

[workflowManager]
org = "deisci"
pullPolicy = "IfNotPresent"
dockerTag = "v2.0.0-beta1"

[logger]
org = "deisci"
pullPolicy = "IfNotPresent"
dockerTag = "git-a3994e4"

[router]
org = "deisci"
pullPolicy = "IfNotPresent"
dockerTag = "git-e674c68"

[fluentd]
org = "deisci"
pullPolicy = "IfNotPresent"
dockerTag = "git-c2910f1"
