apiVersion: v1
kind: Service
metadata:
  name: deis-builder
  namespace: deis
  labels:
    heritage: deis
spec:
  ports:
    - name: ssh
      port: 2222
      protocol: TCP
  selector:
    app: deis-builder
