kind: Service
apiVersion: v1
metadata:
  name: deis-etcd-discovery
  labels:
    name: deis-etcd-discovery
    app: deis
spec:
  ports:
    - name: client
      port: 2381
      targetPort: 2381
      protocol: TCP
  selector:
    name: deis-etcd-discovery
